#run dev server with dev_appserver.py --port=8080 --host=127.0.0.1/ app.yaml
#runtime: go111

#handlers:
#- url: /.*
#  script: _go_app
#  secure: always
#  redirect_http_response_code: 301
#runtime: go111

#handlers:
#  - url: /.*
#    script: auto
#    secure: always
#    redirect_http_response_code: 301
runtime: go
env: flex

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

#https://stackoverflow.com/questions/47125661/pricing-of-google-app-engine-flexible-env-a-500-lesson
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10



